/**
 * Bank API
 * This API exposes endpoints to manage Bank operations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Account } from './account';


export interface User { 
    id?: number;
    firstname?: string;
    lastname?: string;
    cin?: string;
    email?: string;
    password?: string;
    phone?: string;
    birthdate?: string;
    avatar?: string;
    gender?: string;
    address?: string;
    active?: boolean;
    role?: Role;
    role_id?: number;
    accounts?: Set<Account>;
}

